#!/usr/bin/env bash
# _____             _                 _____ _____ 
#|   __|___ ___ ___| |_ ___ _ _ _____|     |   __|
#|__   | . | -_|  _|  _|  _| | |     |  |  |__   |
#|_____|  _|___|___|_| |_| |___|_|_|_|_____|_____|
#      |_|   
# SpectrumOS - Embrace the Chromatic Symphony!
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
# 
#

# Function to install bin scripts
function bin(){
    cd ~/.local/bin
    rm -rfv *
    mkdir -p ~/.local/bin
    cp -ruv ~/dots/bin/* ~/.local/bin
    if [ "$(ls -A ~/.local/bin)" ]; then
        chmod +x ~/.local/bin/*
    fi
}

# Function to copy Qtile files
function qtile_files(){
    mkdir -pv ~/.config/qtile
    cd ~/.config/qtile
    rm -rfv *
    cp -rv ~/dots/qtile/* ~/.config/qtile/
}

# Function to copy dotfiles
function copy_dotfiles(){
    mkdir -pv ~/.cache/wal
    # Shortcuts
    cp -v .shortcuts ~/

    # Picom
    mkdir -p ~/.config/picom
    cp -v ~/dots/picom/picom.conf ~/.config/picom
}

# Function to install Lightdm
function lightdm(){
    sudo pacman -S lightdm lightdm-webkit2-greeter --no-confirm
    sudo cp -v ~/dots/lightdm/lightdm.conf /etc/lightdm/
    sudo cp -v  ~/dots/lightdm/lightdm-webkit2-greeter.conf /etc/lightdm/
    sudo cp -rv ~/dots/lightdm/theme/SpectrumOS /usr/share/lightdm-webkit/themes/
    sudo cp -v ~/.cache/wal/colors.css /usr/share/lightdm-webkit/themes/SpectrumOS/css/
}

# Function to install Rofi files
function rofi(){
    mkdir -pv ~/.config/rofi
    cd ~/.config/rofi
    rm -rfv *
    cp -v ~/dots/rofi/SOS_Colors.rasi ~/.config/wal/templates
    cp -v ~/dots/rofi/*.rasi ~/.config/rofi/
}

# Function to display usage information
function usage() {
    echo "Usage: $0 [--bin] [--qtile] [--dotfiles] [--install-lightdm]"
    exit 1
}



# Main script execution
if [ $# -eq 0 ]; then
    usage
fi

for arg in "$@"; do
    case $arg in
        --bin)
            bin
            ;;
        --qtile)
            qtile_files
            ;;
        --dotfiles)
            copy_dotfiles
            ;;
        --lightdm)
            lightdm
            ;;
        --rofi)
            rofi
            ;;
        *)
            echo "Invalid option: $arg"
            usage
            ;;
    esac
done
