# Shell variables
# Generated by 'wal'
wallpaper='/home/gibranlp/Pictures/Wallpapers/wall3.png'

# Special
background='#131311'
foreground='#f3f0e2'
cursor='#f3f0e2'

# Colors
color0='#131311'
color1='#4E7A8A'
color2='#4391A7'
color3='#A0A897'
color4='#C3BBA3'
color5='#DACBA9'
color6='#E4D3AE'
color7='#f3f0e2'
color8='#aaa89e'
color9='#4E7A8A'
color10='#4391A7'
color11='#A0A897'
color12='#C3BBA3'
color13='#DACBA9'
color14='#E4D3AE'
color15='#f3f0e2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
