--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/gibranlp/Pictures/Wallpapers/wall3.png"

-- Special
background="#131311"
foreground="#f3f0e2"
cursor="#f3f0e2"

-- Colors
color0="#131311"
color1="#4E7A8A"
color2="#4391A7"
color3="#A0A897"
color4="#C3BBA3"
color5="#DACBA9"
color6="#E4D3AE"
color7="#f3f0e2"
color8="#aaa89e"
color9="#4E7A8A"
color10="#4391A7"
color11="#A0A897"
color12="#C3BBA3"
color13="#DACBA9"
color14="#E4D3AE"
color15="#f3f0e2"
