#!/usr/bin/env bash
#####################################################
#  _____             _                 _____ _____  #
# |   __|___ ___ ___| |_ ___ _ _ _____|     |   __| #
# |__   | . | -_|  _|  _|  _| | |     |  |  |__   | #
# |_____|  _|___|___|_| |_| |___|_|_|_|_____|_____| #
#       |_|                                         #
# SpectrumOS - Embrace the Chromatic Symphony!      #
# By: gibranlp <thisdoesnotwork@gibranlp.dev>.      #
# MIT licence                                       #
#                                                   #
#####################################################

# Get Pywal Colors
source "${HOME}/.cache/wal/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

# Sketchybar General Configuratin
sketchybar --bar position=top height=40 blur_radius=20 color="0xcb${color0:1}" topmost=on

# Defaults
default=(
  padding_left=2
  padding_right=2
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.padding_left=5
  icon.padding_right=5
)
sketchybar --default "${default[@]}"

# Apple Logo
source "$CONFIG_DIR/items/apple.sh"

# Sketchybar Aerospace update for Spaces
sketchybar --add event aerospace_workspace_change
source "$CONFIG_DIR/items/aerospace_spaces.sh"

# Menu 
source "$CONFIG_DIR/items/menus.sh"



sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

##### Trigger initial Aerospace workspace highlight #####
FOCUSED_WORKSPACE=$(aerospace focused-workspace)
sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE="$FOCUSED_WORKSPACE"
